# Hello, thanks for using my playbook, hopefully you can help to improve it.

# Install TalosCTL on Ansible node
- name: Install tpi
  hosts: ansible
  gather_facts: true # enables us to gather lots of useful variables: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html
  become: true
  roles:
    - role: install-tpi
      tags: install-tpi

# Install TalosCTL on Ansible node
- name: Install TalosCTL
  hosts: ansible
  gather_facts: true 
  become: true
  roles:
    - role: install-talosctl
      tags: install-talosctl

# Download Talos on Ansible node
- name: Download Talos
  hosts: ansible
  gather_facts: true 
  become: false
  roles:
    - role: download-talos
      tags: download-talos

# Flash Turing RK1 compute modules
- name: Flash RK1
  hosts: ansible
  gather_facts: true 
  become: false
  roles:
    - role: flash-modules
      tags: flash-modules

# Configure Cluster Configuration
- name: Configure Cluster
  hosts: ansible
  gather_facts: true
  roles:
    - role: configure-cluster
      tags: configure-cluster

# Apply Cluster Configuration
- name: Configure Cluster
  hosts: ansible
  gather_facts: true
  roles:
    - role: apply-config
      tags: apply-config

# Configure TalosCTL
- name: Configure TalosCTL
  hosts: ansible
  gather_facts: true
  roles:
    - role: configure-talosctl
      tags: configure-talosctl

# Add Workers
- name: Add Workers
  hosts: ansible
  gather_facts: true
  roles:
    - role: add-workers
      tags: add-workers